#!/bin/bash

logdir="/var/log"


#grepコマンド単体では処理しきれない量のERRORが入った文字列が存在するとした場合を想定
#grep=ファイル中の文字列に対して検索
#拡張子の.logファイルからERRORという文字列を検索
find $logdir -name "*/log" -print | xargs grep "ERROR" /dev/null



