#!/bin/bash

#対象IPアドレスがコマンドライン引数で指定されていなければエラーとして終了
if [ -z "$1" ]; then
	echo "IPアドレスを指定してください" >&2
	exit 1
fi

#テスト対象ネットワークならばpingコマンドを実行する
#192.168.2.0/24および192.168.100.0/24のみをテスト対象とする

case "$1" in
	192.168.2.*|192.168.100.*)
		ping -c 1 "$1" > /dev/null 2>&1

	if [ $? -eq 0 ]; then
		echo "ping to $1 :[OK]"
	else
		echo "ping to $1 :[NG]"
	fi
	;;
	*)
	echo "$1はテスト対象ではありません" >&2
	exit 2
	;;
	esac
