#!/bin/bash

#macではftpコマンド使用不可...

#一時ファイルを作成して、FTP転送し、その転送速度を測定する

＃転送速度を測る一時ファイルのサイズ指定。単位はキロバイト
filesize=1024

#転送速度を測る一時ファイルのファイル名
tmpdata="tmpdata.tmp"
timefile="timecount.tmp"

#転送に用いる一時ファイルを作成する
#ddコマンド=指定された入力から出力へコピーを行う
#if=/dev/zero=入力に/dev/zeroという塗るキャラクタが読みだせるスペシャルデバイスを指定
#of="$filename"=出力にシェル変数filenameで指定されたファイル名を指定
#count=$filesize=シェル変数filesizaで指定した回数だけコピーをおこなう
#bs=1024=コピーをおこなうブロックサイズ。ここでは1024バイト
dd if=/dev/zero of="$tmpdata" count=$filesiza bs=1024 2> /dev/null

#ftp接続してファイルをPUTする
server="192.168.100.1"
user="user1"
password="xxxxxxxx"


echo "Filesize: $filesize (KB)"
echo "FTP Server:$server"


#<<__EOT__からヒアドキュメント
#time=実行時間の計測
#-pオプション=秒数のみを表示
(time -p ftp -n "$server") << __EOT__ 2> "$timefile"

user "$user" "$password"
binary
put "$tmpdata"
__EOT__

#timeコマンドの出力結果から実時間を取得し、割り算を行って速度を求める
realtime=$(awk '/^real / {print $2}' "$timefile")
speed=$(echo "${filesize}/${realtime}" | bc)
echo "Transfer Speed: $speed (KB/sec)"

#転送一時ファイルの削除
rm -f "$tmpdata" "$timefile"
