#!/bin/bash

#ログファイルが存在しなければs終了

if [ ! -f "$logfile" ]; then

	echo "対象のログフィルが存在しません : $logfile" >&2
	exit 1
fi

#ログファイルからGETメソッドで取得されたファイルのアクセス回数を集計する
#awkコマンドでファイルを取り出し、sort+uniqでカウント後に降順ソートする
awk '$6=="\"GET" {print $7}' "$logfile" | sort | uniq -c | sort -nr
