#!/bin/bash

#普通ヒアドキュメント内にタブやスペースを含めて無視させることはできないが、
#<<-EOTとかくことで、タブを無視させ、このシェルないでヒアドキュメントが非常に見やすくなる

#コマンドラインの引数チェック

if [ -z "$1" ]; then
	echo "title要素を引数で指定してください" >&2
	exit 1
else
	#コマンドライン引数$1の文字列をtitle要素に入れて表示
	#ヒアドキュメントに-指定して、行頭タブを無視してインデントしている
	cat <<-EOT
	<html>
	<head>
	<title>$1</title>
	</head>
	<body>
	<p>Auto HTML sample</p>
	</body>
	EOT
fi

