#!/bin/bash

#echoコマンドをシェル変数　ECHOに置き換える

#macのオペレーティングシステムはDarwin

#echoコマンドのパスを環境によって変えてシェル変数ECHOに代入する


#uname=オペレーティングシステムを表示してくれる
#
case $(uname -s) in
	Darwin)
		#macではecho -n に対応していない。だからechoをそのまま使用するのではなく、ECHOにechoをケースごとに代入している。
		#macの場合はシェルビルトインコマンドではなく、/bin/echoを使用
		ECHO="/bin/echo"
		;;	

	*)
		ECHO="echo"
		;;
	esac


#macのシェルビルトインコマンドはecho -n （改行させない）に対応していないが、/bin/echoを使用するコマンドに使用したことで、
#-nオプションがしようできるようになった
$ECHO -n "ここは改行をしない"
$ECHO  "メッセージです"

