#!/bin/bash

#コマンドの終了ステータスがゼロでない場合は、スクリプトを直ちに終了する
#set -e = コマンドの終了ステータスが０出ない場合にただちにスクリプトを終了
set -e

#削除ファイルの格納ディレクトリをミスタイプしている設定

deldir="$HOME/documents/unix_lessons/test/test094"

#ディレクトリ$deldirに移動して、拡張子.logのファイルを削除する
#set -e しているため、ディレクトリ移動に失敗すればrmコマンドは実行されない
cd "$deldir"
rm -f *.log
