#!/bin/bash

#ファイルを指定するコマンドライン引数をチェック

if [ ! -f "$1" ]; then

	echo "ファイルがありません: $1" >&2
	exit 2
fi


#ファイル名から属するrmpパッケージ名を取得する

pkgname=$(rpm -qf "$1")

#rpm ーqfコマンドの結果でパッケージ名を表示する
if [ $? -eq 0 ] ; then
	echo "$1 -> $pkgname"
else
	echo "$1 はパッケージに属していません" >&2
	exit 1
fi

