#!/bin/bash


#ifconfigコマンドで有効なインターフェイスを表示して、
#awkコマンドでインターフェイス名とIPアドレスを抽出する

#LANGにCを指定しているのは、ubuntuなどではデフォルトだと結果が日本語表記されて、ifconfigでipアドレスを取り出すのが難しくなるため。
#行末に\をおくと改行できる！改行の後のコマンドにつづけられる

#awkでifconfigでとりだした出力を整形
#行頭が空白じゃなくて英語の行を抽出

#ネットワークインターフェース名を抜き出し

LANG=C /sbin/ifconfig |\
 awk '/^[a-z]/{print $1}' | awk 'sub(/.$/,"",$1)'


#ipアドレスを抜き出し
ifconfig | awk '/inet / {split($2,arr,":");print arr[1]}'
