#!/bin/bash

#bashのブレース展開で{}、IPアドレスを作成する
for ipaddr in 192.168.100.{1..5}
do
	ping -c 1 "$ipaddr" > /dev/null 2>&1

	if [ $? -eq 0 ]; then
		echo "[OK] Ping -> $ipaddr"
	else
		echo "[NG]  Ping -> $ipaddr"
	fi
done
