#!/bin/bash

#カレンダーから選択した日付のログファイルを削除するシェルスクリプト

#logファイルがそんざいしなければ　作成
if [[ ! -f $HOME/documents/unix_lessons/test/no009set/log ]]; then
  # 実行する処理、以下は例
  mkdir   $HOME/documents/unix_lessons/test/no009set/log  
fi 



LOG_DIR=./log

#dialogコマンドでカレンダー入力
#選択日付は標準エラー出力にでるため，一時ファイルへリダイレクトする

dialog --calendar "Select Date" 2 60 2> cal.tmp


#カレンダー機能では　日/月/年(欧米形式)　形式で出力されるため，これを
#年月日（日本形式）に整形する

date_str=$(awk -F / '{print $3$2$1}' cal.tmp)

#カレンダーの日付選択がキャンセルされた場合はテンポラリファイルを削除し終了
if [ -z "$date_str" ]; then
	rm -f cal.tmp
	exit
fi


rm  ${LOG_DIR}/$date_str.log

#テンポラリファイルを削除する
rm -f cal.tmp
