#!/bin/bash

#監視するディスク使用量の閾値パーセンテージ
used_limit=90
#dfコマンドの出力結果一時ファイル名
tmpfile="df.tmp.$$"

#dfコマンドでディスク容量を表示。1行目はヘッダなので除外する

df -P | awk 'NR >= 2{print $5,$6}' > "$tmpfile"

#dfコマンドの出力の一時ファイルから、使用率を確認する
while read percent mountpoint
do
	#"31%"を"31"に、末尾の%記号を削除する
	percent_val=${percent%\%}

	#ディスク使用量が規定値以上ならアラート
	if [ "$percent_val" -ge "$used_limit" ]; then
		#現在日付をいい感じのフォーマット表示する
		date_str=$(date '+%Y/%m/%d %H:%M:%S')
		
		echo "[$date_str] Disk capacity Alert: $mountpoint ($percent used)"
		$HOME/documents/unix_lessons/test/no116set/alert.sh
	fi
done < "$tmpfile"


#一時ファイル削除
#rm -f "$tmpfile"
