#!/bin/bash

#３つのホストに並列してpingを実行する。6回実行するためそれぞれ約５秒間の待ち時間がかかる
#プロントで作業していたからいつもとちがう〜ipアドレス
#待ち時間の短縮のため、3つのpingコマンドそれぞれの最後に&をつけて、pingコマンドをバックグラウンドで実行


ping -c 6 10.248.5.72 > host1.log &
ping -c 6 10.248.5.72 > host2.log &
ping -c 6 10.248.5.72 > host3.log &

#３つのpingコマンドが終了するまで待ち、同期をとる

wait

#pingコマンドの結果を表示する

cat host1.log host2.log host3.log

