#!/bin/bash

#数値データの書かれたcsvファイルから平均値を取得する

#csvファイルが存在しなければ終了
if [ ! -f "$1" ] ;then
	echo "対象のCSVファイルが存在しません: $1" >&2
	exit 1
fi

#拡張子を除いたファイル名を取得
filename=${1%.*}

#NR=行数
#全て足し合わせる
#awkの{}は各行で実行される
#END{}は最終行を読んだ後に実行される
awk -F, '{sum += $3} END{print sum / NR}' "$1" > ${filename}.avg
