#!/bin/bash


#一時ファイルを利用するスクリプトで、正常終了、強制終了ともに共通の終了処理(tmpfileを削除)を記述したい時

#一時ファイルを定義し、ファイルの中をからに初期化する
# : > はファイルの初期化
#:=ヌル
#$$はプロセスID
tmpfile="calctmp.$$"

: > "$tmpfile"

#トラップの設定。終了時に一時ファイルを削除する
#EXITシグナル＝bash で使用できる擬似シグナル！！
#正常終了でも、異常終了いずれの場合にも発生する

trap 'rm -f "$tmpfile"' EXIT

#長い計算を行う外部スクリプトを実行する
./calcA.sh >> "$tmpfile"
./calcB.sh >> "$tmpfile"

#計算結果を足し合わせて、最終数値を計算する
awk '{sum += $1} END{print sum}' "$tmpfile"
